### ISSUE TITLE
Attention is all you need

### ISSUE THREAD

**Issue by Kiteflyingee** [zhedongzheng/finch#10]
I am trying to modify your code to fit the English data set.
I modified DataLoader.py ，added English word segmentation.But when I train the model, I get an error.

INFO:tensorflow:loss = 7.306507, step = 0
INFO:tensorflow:lr = 0.001
ERROR:tensorflow:Model diverged with loss = NaN.
ne, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute':
None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E5D23D9470>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Traceback (most recent call last):
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 1425, in done
    fut.result()
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 157, in callback
    x = next(it)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 2070, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 311, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 41
Traceback (most recent call last):
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 1425, in done
    fut.result()
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 157, in callback
    x = next(it)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 2070, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 311, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 41
Traceback (most recent call last):
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 1425, in done
    fut.result()
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 157, in callback
    x = next(it)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 2070, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 311, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 41
Traceback (most recent call last):
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 1425, in done
    fut.result()
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\futures.py", line 157, in callback
    x = next(it)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 2070, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\wrapper.py", line 311, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 41
WARNING:tensorflow:From C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated
and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-03-26 12:58:05.482552: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-03-26 12:58:06.511141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-03-26 12:58:06.528029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-26 12:58:08.067124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-26 12:58:08.101398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-03-26 12:58:08.116357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-03-26 12:58:08.133051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3015 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id:
0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be
removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\89534\AppData\Local\Temp\tmpc8cb1xnq\model.ckpt.
2019-03-26 13:02:24.506298: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
INFO:tensorflow:loss = 7.306507, step = 0
INFO:tensorflow:lr = 0.001
ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
    run()
  File "c:\Users\89534\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\CDisk\Documents\GitHub\finch\src_nlp\tensorflow\attn_is_all_u_need\train_dialog.py", line 36, in <module>
    main()
  File "d:\CDisk\Documents\GitHub\finch\src_nlp\tensorflow\attn_is_all_u_need\train_dialog.py", line 30, in main
    shuffle = True))
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "C:\Users\89534\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 753, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
![image](https://user-images.githubusercontent.com/12490322/54972661-87fb7280-4fc7-11e9-8ba0-e14750ccbbc2.png)

The code I am modifying may have a problem. How can I modify the code to enable it to train the English corpus?Thanks.i write chatbot for the first time

**Comment by Kiteflyingee** [comment]
Sorry, the problem is caused by my data set, I have solved it.
